title: Tejas Maraliga # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Incoming freshman at the University of Texas at Austin in Austin, TX
  <br><br>
  Senior Systems Developer at The Internship Initiative LLC.
  <br><br>
  <a href="https://www.linkedin.com/in/tejas-m-ba4b23131/">View My LinkedIn Profile</a>
  <br><br>
  <a href="https://interninit.com">View The Internship Initiative LLC.</a>



theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
