title: Tejas Maraliga # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Sophomore at the University of Texas at Austin in Austin, TX
  <br><br>
  VP of Tech at The Internship Initiative LLC.
  <br><br>
  Competition Organizer at The Scholastic Artificial Intelligence League
  <br><br>
  <a href="https://www.linkedin.com/in/tejas-m-ba4b23131/">View My LinkedIn Profile</a>
  <br><br>
  <a href="https://interninit.com">View The Internship Initiative LLC.</a>
  <br><br>
  <a href="https://liftoff2021.com">View SAILea Liftoff 2021</a>
  <br><br>
  <a href="/assets/resume.pdf" target="_blank">Download my resumé</a>  


theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
